create table admin_user (
    id bigint generated by default as identity primary key,
    username varchar(80) not null unique,
    password_hash varchar(200) not null,
    display_name varchar(120) not null,
    enabled boolean not null default true,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table counselor (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    avatar_url varchar(500),
    summary varchar(500),
    specialties varchar(500),
    service_audience varchar(300),
    counseling_methods varchar(200),
    counseling_style varchar(500),
    price_and_duration varchar(200),
    qualifications text,
    sort_order integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table service_item (
    id bigint generated by default as identity primary key,
    name varchar(160) not null,
    summary varchar(500),
    suitable_for varchar(500),
    common_topics varchar(500),
    counseling_methods varchar(200),
    seo_title varchar(200),
    seo_description varchar(500),
    seo_keywords varchar(300),
    sort_order integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table article_category (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    slug varchar(120) not null unique,
    sort_order integer not null default 0,
    status varchar(30) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table article (
    id bigint generated by default as identity primary key,
    category_id bigint,
    title varchar(220) not null,
    slug varchar(180) not null unique,
    cover_url varchar(500),
    summary varchar(500),
    content text,
    seo_title varchar(200),
    seo_description varchar(500),
    seo_keywords varchar(300),
    status varchar(30) not null,
    published_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_article_category foreign key (category_id) references article_category(id)
);

create table appointment (
    id bigint generated by default as identity primary key,
    nickname varchar(120) not null,
    contact varchar(160) not null,
    city varchar(120),
    age_range varchar(80),
    consultation_target varchar(80),
    concern_direction varchar(160),
    consultation_method varchar(80),
    preferred_time varchar(160),
    preferred_counselor_id bigint,
    accepts_recommendation boolean not null default true,
    problem_summary text,
    privacy_agreed boolean not null,
    emergency_acknowledged boolean not null,
    status varchar(30) not null,
    internal_note text,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_appointment_counselor foreign key (preferred_counselor_id) references counselor(id)
);

create table site_config (
    id bigint generated by default as identity primary key,
    config_key varchar(120) not null unique,
    config_value text,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table upload_file (
    id bigint generated by default as identity primary key,
    original_name varchar(255) not null,
    stored_name varchar(255) not null,
    content_type varchar(120) not null,
    size_bytes bigint not null,
    public_url varchar(500) not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table operation_log (
    id bigint generated by default as identity primary key,
    actor varchar(120),
    action varchar(120) not null,
    target_type varchar(120),
    target_id bigint,
    detail text,
    created_at timestamp not null,
    updated_at timestamp not null
);

