create table analytics_event (
    id bigint generated by default as identity primary key,
    event_name varchar(120) not null,
    page_path varchar(500),
    target varchar(200),
    created_at timestamp not null,
    updated_at timestamp not null
);

