create table chat_session (
    id bigint generated by default as identity primary key,
    visitor_name varchar(120),
    visitor_contact varchar(160),
    topic varchar(160),
    status varchar(30) not null,
    crisis_flagged boolean not null default false,
    ai_enabled boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null
);

create table chat_message (
    id bigint generated by default as identity primary key,
    session_id bigint not null,
    role varchar(30) not null,
    content text not null,
    crisis_flagged boolean not null default false,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_chat_message_session foreign key (session_id) references chat_session(id)
);

